"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
Object.defineProperty(exports, "__esModule", { value: true });
var platform_browser_1 = require("@angular/platform-browser");
var core_1 = require("@angular/core");
// By default, the app generated by ng init will include the FormsModule, here we’re requiring the ReactiveFormsModule as well
var forms_1 = require("@angular/forms");
var http_1 = require("@angular/http");
// Include the components we created
var form_interet_pro_html_1 = require("./form/form.interet-pro.html");
var form_interet_etu_html_1 = require("./form/form.interet-etu.html");
var form_info_comp_pro_html_1 = require("./form/form.info-comp-pro.html");
var form_info_comp_etudiant_html_1 = require("./form/form.info-comp-etudiant.html");
var form_formvalidations_1 = require("./form/form.formvalidations");
var AppModule = (function () {
    function AppModule() {
    }
    return AppModule;
}());
AppModule = __decorate([
    core_1.NgModule({
        declarations: [
            AppComponent,
            // Declare the three components as part of the root NgModule
            form_interet_pro_html_1.InteretPro,
            form_interet_etu_html_1.InteretEtudiant,
            form_info_comp_pro_html_1.InfoCompPro,
            form_info_comp_etudiant_html_1.InfoCompEtudiantComponent,
            form_formvalidations_1.FormValidationComponent,
        ],
        imports: [
            platform_browser_1.BrowserModule,
            forms_1.FormsModule,
            // Including the ReactiveFormsModule in our application
            forms_1.ReactiveFormsModule,
            http_1.HttpModule
        ],
        providers: [],
        bootstrap: [AppComponent]
    })
], AppModule);
exports.AppModule = AppModule;
